import './globals.css'

import {Auth} from '@aws-amplify/auth'
import {Poppins} from 'next/font/google'
import {App} from '@/app/app'
import StyledComponentsRegistry from '@/app/registry'
import {CONFIG} from '@/config'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600'],
})

Auth.configure({
  mandatorySignIn: false,
  region: 'eu-west-2',
  userPoolId: CONFIG.AMPLIFY.USER_POOL_ID,
  identityPoolId: CONFIG.AMPLIFY.IDENTITY_POOL_ID,
  userPoolWebClientId: CONFIG.AMPLIFY.USER_WEB_CLIENT_ID,
})

export const metadata = {
  title: 'Memba | Memberships done right.',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: JSX.Element}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={poppins.className}>
        <StyledComponentsRegistry>
          <App>{children}</App>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
