import './globals.css'

import {Auth} from '@aws-amplify/auth'
import {Poppins} from 'next/font/google'
import {App} from '@/app/app'
import StyledComponentsRegistry from '@/app/registry'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600'],
})

Auth.configure({
  mandatorySignIn: false,
  region: 'eu-west-2',
  userPoolId: 'eu-west-2_H6F7KWKl8',
  identityPoolId: 'eu-west-2:c66b9ccc-9141-4ac7-a274-be74a27940bc',
  userPoolWebClientId: '712hh8ocdqmu3g4se27deg555i',
})

export const metadata = {
  title: 'Memba | Memberships done right.',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: JSX.Element}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={poppins.className}>
        <StyledComponentsRegistry>
          <App>{children}</App>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
